// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CheckSiteMenuInDetailFeature : object, Xunit.IClassFixture<CheckSiteMenuInDetailFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CheckSiteMenuInDetail.feature"
#line hidden
        
        public CheckSiteMenuInDetailFeature(CheckSiteMenuInDetailFeature.FixtureData fixtureData, AutomationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "CheckSiteMenuInDetail", "\tFull test to check all left hand side menu", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Check Main Menu in Detail")]
        [Xunit.TraitAttribute("FeatureTitle", "CheckSiteMenuInDetail")]
        [Xunit.TraitAttribute("Description", "Check Main Menu in Detail")]
        [Xunit.TraitAttribute("Category", "checkHousingPageComponents")]
        [Xunit.InlineDataAttribute("albury", new string[0])]
        [Xunit.InlineDataAttribute("baw-baw", new string[0])]
        [Xunit.InlineDataAttribute("bass-coast", new string[0])]
        [Xunit.InlineDataAttribute("broken-hill", new string[0])]
        [Xunit.InlineDataAttribute("snowy-monaro", new string[0])]
        [Xunit.InlineDataAttribute("knox", new string[0])]
        [Xunit.InlineDataAttribute("whittlesea", new string[0])]
        [Xunit.InlineDataAttribute("glenorchy", new string[0])]
        [Xunit.InlineDataAttribute("salisbury", new string[0])]
        [Xunit.InlineDataAttribute("south-gippsland", new string[0])]
        [Xunit.InlineDataAttribute("midcoast", new string[0])]
        [Xunit.InlineDataAttribute("frankston", new string[0])]
        [Xunit.InlineDataAttribute("bayside", new string[0])]
        [Xunit.InlineDataAttribute("mornington-peninsula", new string[0])]
        [Xunit.InlineDataAttribute("cardinia", new string[0])]
        [Xunit.InlineDataAttribute("townsville", new string[0])]
        [Xunit.InlineDataAttribute("shoalhaven", new string[0])]
        [Xunit.InlineDataAttribute("east-gippsland", new string[0])]
        [Xunit.InlineDataAttribute("tamworth", new string[0])]
        [Xunit.InlineDataAttribute("gunnedah", new string[0])]
        [Xunit.InlineDataAttribute("coffs-harbour", new string[0])]
        [Xunit.InlineDataAttribute("g21-region", new string[0])]
        public virtual void CheckMainMenuInDetail(string alias, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "checkHousingPageComponents"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("alias", alias);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Main Menu in Detail", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given(string.Format("an input client alias with \"{0}\"", alias), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
 testRunner.When("I go to their page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
 testRunner.Then("their site should be valid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "MenuText"});
                table2.AddRow(new string[] {
                            "Housing Demand"});
                table2.AddRow(new string[] {
                            "Housing Supply"});
                table2.AddRow(new string[] {
                            "Housing Consumption"});
                table2.AddRow(new string[] {
                            "Prices & Incomes"});
                table2.AddRow(new string[] {
                            "Housing Stress & Need"});
                table2.AddRow(new string[] {
                            "Affordability Monitor"});
#line 9
 testRunner.And("it should have the menu", ((string)(null)), table2, "And ");
#line hidden
#line 17
 testRunner.And("sub-menu should work", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CheckSiteMenuInDetailFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CheckSiteMenuInDetailFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
